[package]
name = "protocol"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
chrono = "0.4"
parking_lot = "0.12"
anyhow = "1"
serde_json = "1"
models = { path = "../models" }
prost = "0.12"

[build-dependencies]
prost-build = "0.12"
protoc-bin-vendored = "3"
